name: tests

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: stable
          install-dependencies: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: xvfb-run --auto-servernum npm test -- --ci --color

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
          retention-days: 1
